# Generated by Django 4.2.9 on 2024-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_register_address_alter_register_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tourcode', models.CharField(max_length=20)),
                ('tourname', models.CharField(max_length=40)),
                ('tourpackage', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Package_table',
            },
        ),
    ]
