# Generated by Django 4.2.9 on 2024-02-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_packages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packages',
            table='package_table',
        ),
    ]
