# Generated by Django 4.2.9 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_packages_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='tourcode',
            field=models.IntegerField(max_length=20),
        ),
    ]
