# Generated by Django 4.2.9 on 2024-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_packages_tourcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='tourcode',
            field=models.CharField(max_length=20),
        ),
    ]
