# Generated by Django 4.2.9 on 2024-03-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_packages_tourcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='rs,_table',
        ),
    ]
